name: Build Samsung S20+ Kernel with Clang

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential curl flex git libncurses-dev libssl-dev libelf-dev python3 python3-pip unzip

      - name: Download Android NDK (Clang)
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip -qq android-ndk-r23b-linux.zip
          echo "NDK=$(pwd)/android-ndk-r23b" >> $GITHUB_ENV

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export NDK=$NDK
          export PATH=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export CC=aarch64-linux-android30-clang
          export CROSS_COMPILE=aarch64-linux-android-
          make mrproper
          make exynos990-x1s_defconfig
          make -j$(nproc) CC=$CC CROSS_COMPILE=$CROSS_COMPILE

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: |
            arch/arm64/boot/Image*
            arch/arm64/boot/dts/*.dtb
